/* THIS FILE HAS BEEN GENERATED AUTOMATICALLY,
 * DO NOT EDIT THIS FILE MANUALLY. ALL MODIFICATIONS WILL
 * BE OVERWRITTEN. */ 


/* This file observes the license used by the project */
/* In the case of more than one conflicting license, this
 * file is property of the public domain */


#ifndef __BUILD_DEF_HDR__
#define __BUILD_DEF_HDR__

#ifdef __cplusplus
extern("C") {
#endif

#ifdef __cplusplus
}
#endif

#endif

